# Boilerplate code generated by OVITO Pro 3.10.6
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
import numpy as np

# Data import:
file = sys.argv[1]
folder = os.path.basename(file).split('.')
split = folder[0].split('_')
hconc = int(split[0][2:])
heconc = int(split[1][2:])
dpa = int(folder[1]) * 0.0002

pipeline = import_file(file)
# Expression selection:
pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'ParticleType!=1'))

# Cluster analysis:
pipeline.modifiers.append(ClusterAnalysisModifier(
    cutoff = 3.0, 
    only_selected = True, 
    sort_by_size = True))

data = pipeline.compute()

if data.tables != None:
    # print(data.tables['clusters'])
    cluster_size = np.array(data.tables['clusters'].y.T).astype(int)
    
if len(cluster_size) > 0:
    n_gases = np.sum(cluster_size)
    max_cluster = cluster_size.max()
else:
    n_gases = 0
    max_cluster = 0

print('%d %d %f %d %d' % (hconc, heconc, dpa, max_cluster, n_gases))

with open('cluster_data.log', 'a') as file:
    file.write('%d %d %f %d %d \n' % (hconc, heconc, dpa, max_cluster, n_gases))
    